apiVersion: v1
kind: Pod
metadata:
  name: secrets-demo-pod
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password